# Generated by Django 5.2.5 on 2026-02-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_engine_companyengine'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
