# Generated by Django 5.2.5 on 2026-02-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_add_conversation_and_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='applies_to',
            field=models.CharField(choices=[('prompts', 'Prompts'), ('files', 'Files'), ('both', 'Both')], default='both', max_length=20),
        ),
    ]
