# Generated by Django 5.2.5 on 2026-02-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_add_applies_to_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
