# Generated by Django 5.2.5 on 2026-02-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_add_avatar_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_engine',
            field=models.ForeignKey(blank=True, help_text='Default AI engine for chat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='front.companyengine'),
        ),
    ]
