# Generated by Django 5.2.5 on 2026-02-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_add_default_engine_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('supports_vision', models.BooleanField(default=False)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='front.engine')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('engine', 'model_id')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='default_model',
            field=models.ForeignKey(blank=True, help_text='Default AI model for chat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='front.enginemodel'),
        ),
    ]
