# Generated by Django 5.2.5 on 2026-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_seed_default_engines'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyengine',
            name='name',
            field=models.CharField(blank=True, help_text='Custom name for this engine (defaults to engine name)', max_length=100),
        ),
    ]
