# Generated by Django 4.2.28 on 2026-02-13 20:30

from django.db import migrations
import front.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_encrypt_api_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyengine',
            name='api_key',
            field=front.encrypted_fields.EncryptedCharField(help_text='API key (stored encrypted)', max_length=512),
        ),
    ]
