# Generated by Django 4.2.28 on 2026-02-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_alter_companyengine_api_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyengine',
            unique_together=set(),
        ),
    ]
