# Generated by Django 4.2.28 on 2026-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_remove_companyengine_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='action',
            field=models.CharField(choices=[('block', 'Block'), ('consent', 'Consent')], default='block', help_text='Block stops the message. Consent asks the user for confirmation before sending.', max_length=20),
        ),
    ]
