# Generated by Django 4.2.28 on 2026-02-18 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_seed_default_rules_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObfuscationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_url', models.URLField(help_text='Base URL del servicio PasteGuard (ej: https://pasteguard.com)')),
                ('detect', models.CharField(choices=[('pii', 'PII'), ('secrets', 'Secrets'), ('both', 'PII & Secrets')], default='both', max_length=20)),
                ('language', models.CharField(blank=True, default='', help_text='Idioma para detección (vacío=auto-detectar)', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obfuscation_configs', to='front.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
