# Generated by Django 4.2.28 on 2026-02-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0021_obfuscationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('rule', 'Rule'), ('obfuscation', 'Obfuscation')], default='rule', max_length=20),
        ),
    ]
