# Generated by Django 4.2.28 on 2026-02-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_alert_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='General context sent to all engines in every conversation.', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Department-specific context, appended after the company context.', null=True),
        ),
    ]
